# Generated by Django 4.0 on 2022-01-02 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='predresults',
            old_name='bill_amt_1',
            new_name='bill_amt1',
        ),
        migrations.RenameField(
            model_name='predresults',
            old_name='bill_amt_2',
            new_name='bill_amt2',
        ),
        migrations.RenameField(
            model_name='predresults',
            old_name='bill_amt_3',
            new_name='bill_amt3',
        ),
        migrations.RenameField(
            model_name='predresults',
            old_name='bill_amt_4',
            new_name='bill_amt4',
        ),
        migrations.RenameField(
            model_name='predresults',
            old_name='bill_amt_5',
            new_name='bill_amt5',
        ),
        migrations.RenameField(
            model_name='predresults',
            old_name='bill_amt_6',
            new_name='bill_amt6',
        ),
        migrations.RenameField(
            model_name='predresults',
            old_name='pay_amt_1',
            new_name='pay_amt1',
        ),
        migrations.RenameField(
            model_name='predresults',
            old_name='pay_amt_2',
            new_name='pay_amt2',
        ),
        migrations.RenameField(
            model_name='predresults',
            old_name='pay_amt_3',
            new_name='pay_amt3',
        ),
        migrations.RenameField(
            model_name='predresults',
            old_name='pay_amt_4',
            new_name='pay_amt4',
        ),
        migrations.RenameField(
            model_name='predresults',
            old_name='pay_amt_5',
            new_name='pay_amt5',
        ),
        migrations.RenameField(
            model_name='predresults',
            old_name='pay_amt_6',
            new_name='pay_amt6',
        ),
    ]
